[server]
headless = true
port = $PORT
enableCORS = false

[build]
commands = [
    "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y",  # Install rustup
    "source $HOME/.cargo/env",  # Add Cargo to PATH
    "rustup update stable" # Ensure we have latest stable Rust
]
